<?php
namespace app\index\controller;

use think\Controller;
use think\Request;

class Base extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->request = Request::instance();
        $token = $this->request->only(['token']);
        if (empty($token)){
            echo json_encode(['code'=>404,'msg'=>'token为空']);die;
        }else{
            echo json_encode(['code'=>404,'msg'=>'chengg']);
        }
    }
}


